version: '3'
services:
    app:
        build: .
        ports:
            - '3000:3000'
        volumes:
            # Left side: Host machine path, Right side: Container path
            - './src/data:/usr/src/app/data'
